spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: sa
    password: sa
  jpa:
    show-sql: true

application:
  config:
    rest:
      clients:
        balance:
          host: http://localhost:1010
        card:
          host: http://localhost:1020

management:
  metrics:
    enable:
      all: false
      jvm: false