server:
  servlet:
    context-path: /payment-processor/api

spring:
  application:
    name: payment-processor
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl
  liquibase:
    enabled: true
    default-schema: payment_processor
  main:
    banner-mode: off

application:
  config:
    rest:
      evict-idle-connection-timeout: PT5M
      max-connections-per-route: 20
      max-connections-total: 40
      connection-timeout: PT60S
      connection-request-timeout: PT30S
      socket-timeout: PT60S
      clients:
        balance:
          host: http://localhost:1010
          endpoints:
            user-balance: "/v1/balance/{userId}"
        card:
          host: http://localhost:1020
          endpoints:
            card-validation: "/v1/card/validation"
    service:
      operation-lock:
        cache:
          ttl: PT6H
          striped-lock-size: 512
          max-size: 10_000
        max-retries: 5
      velocity-check:
        counter-window-seconds: 10
        max-request-count: 5

management:
  endpoints:
    web:
      exposure:
        include: health,metrics