server:
  servlet:
    context-path: /payment-processor/api

spring:
  application:
    name: payment-processor
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl
  liquibase:
    enabled: true
    default-schema: payment_processor
  main:
    banner-mode: off

application:
  config:
    rest:
      evict-idle-connection-timeout: PT5M
      max-connections-per-route: 20
      max-connections-total: 40
      connection-timeout: PT60S
      connection-request-timeout: PT30S
      socket-timeout: PT60S
      clients:
        balance:
          endpoints:
            user-balance: "/v1/balance/{userId}"
        card:
          endpoints:
            card-validation: "/v1/card/validation"
    service:
      operation-lock:
        cache:
          ttl: PT6H
          striped-lock-size: 512
          max-size: 10_000
        max-retries: 5
      velocity-check:
        counter-window-seconds: 10
        max-request-count: 5

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 50
        minimumNumberOfCalls: 25
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        slowCallRateThreshold: 80
        slowCallDurationThreshold: 3s
        ignoreExceptions:
          - com.zilch.interview.exception.BalanceResponseException
          - com.zilch.interview.exception.CardResponseException
    instances:
      balanceService:
        baseConfig: default
      cardService:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 500ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        enableRandomizedWait: true
        randomizedWaitFactor: 0.5
        ignoreExceptions:
          - com.zilch.interview.exception.BalanceResponseException
          - com.zilch.interview.exception.CardResponseException
    instances:
      balanceService:
        baseConfig: default
      cardService:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
        cancelRunningFuture: true
    instances:
      balanceService:
        baseConfig: default
      cardService:
        baseConfig: default